version: '2'
services:
  rocketmq_namesrv:
    extra_hosts:
      - '10-8-48-18:10.8.48.18'
    restart: always
    #oom-kill-disable: true
    image: 'lihongwansui/rq_namesrv:4.1.0'
    ports:
      - '9876:9876'
    network_mode: "host"
  rocketmq_broker:
    extra_hosts:
      - '10-8-48-18:10.8.48.18'
    restart: always
    #oom-kill-disable: true
    image: 'lihongwansui/rq_broker:4.1.0'
    network_mode: "host"
    environment:
      - nameservers=10.8.48.18:9876
      - BROKERIP1=10.8.48.18
    ports:
      - '10909:10909'
      - '10911:10911'
